name: Testing bucket directories
on:
    push:

jobs:
    create_backend-and-state:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2
            
            - name: create backend
              run: |
                BUCKET_NAME="ephemeral-dev-environment-tfstate-bucket"
                REGION="us-east-1"
                TABLE_NAME="home-service-v2-terraform-lock"

                # check if the bucket exists and create it if it doesn't
                if aws s3api --profile personal-aws head-bucket --bucket "$BUCKET_NAME" 2>/dev/null; then
                    echo "Bucket $BUCKET_NAME already exists."
                else
                    echo "Bucket $BUCKET_NAME does not exist. Creating..."
                    aws s3api --profile personal-aws create-bucket --bucket "$BUCKET_NAME" --region "$REGION"
                    aws s3api --profile personal-aws put-bucket-encryption --bucket "$BUCKET_NAME" --server-side-encryption-configuration '{"Rules":[{"ApplyServerSideEncryptionByDefault":{"SSEAlgorithm":"AES256"}}]}'
                    echo "Bucket $BUCKET_NAME created and encryption enabled."
                fi

                # Check if the DynamoDB table exists
                if aws dynamodb  --profile personal-aws describe-table --table-name "$TABLE_NAME" --query "Table.TableStatus" --output text 2>/dev/null; then
                    echo "Table $TABLE_NAME already exists."
                else
                    echo "Table $TABLE_NAME does not exist. Creating..."
                    aws dynamodb --profile personal-aws create-table \
                        --table-name "$TABLE_NAME" \
                        --attribute-definitions AttributeName=LockID,AttributeType=S \
                        --key-schema AttributeName=LockID,KeyType=HASH \
                        --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5 \
                        --region "$REGION"
                    echo "Table $TABLE_NAME created."
                fi
            
            - name: terraform plan
              run: |
                STATE_PATH=$GITHUB_REF_NAME
                terraform init -backend-config="key=$STATE_PATH/terraform.tfstate"   || { echo "Failed to initialize Terraform configuration"; exit 1; }
                terraform plan
        
            